---
- hosts: all
  become: yes
  gather_facts: no

  vars:
    dbname: bieraustin
    dbuser: bieraustin
    dbpassword: bieraustin123!

  tasks:
    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
        - libsqlite3-dev
        - vim
        - postgresql=9.4+164.pgdg12.4+1
        - libpq-dev
        - python-psycopg2
        - python3-pip

    - name: Allow passwordless postgres user command on localhost
      lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
        line="local   all             postgres                                trust"
        regexp="local *all *postgres.*"
        state=present

    - name: Allow passwordless postgres user command on localhost
      lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
        line="local   all             all                                     trust"
        regexp="local *all *all.*"
        state=present

    - service:
        name: postgresql
        state: reloaded

    - name: ensure user is created
      command: psql -U postgres -c "CREATE USER {{dbuser}} WITH PASSWORD '{{dbpassword}}';"
      ignore_errors: True

    - name: ensure db
      command: createdb -O {{dbuser}} -U postgres {{dbname}}
      ignore_errors: True

    - name: create /home/vagrant/.pam_environment file
      file:
          path: /home/vagrant/.pam_environment
          owner: vagrant
          group: vagrant
          mode: 0644
          state: touch

    - name: setup environment variables
      lineinfile: dest=/home/vagrant/.pam_environment
                  line='{{item}}'
      with_items:
        - 'DATABASE_URL=postgres://{{dbuser}}:{{dbpassword}}@localhost/{{dbname}}'

- hosts: all
  become: yes
  become_user: vagrant

  tasks:
    - name: automatically go to /vagrant
      lineinfile: dest=/home/vagrant/.bashrc
                  line='cd /vagrant/'
